blueprint:
  name: Solarüberschussladen des Warmwasserboilers
  description: >
    Steuerung des Warmwasserboilers basierend auf Solarüberschuss und Batterieladezustand.
  domain: automation
  input:
    legionella_temperature:
      name: Legionellen Temperatur
      selector:
        entity:
          domain: input_number
    normal_temperature:
      name: Normale Temperatur
      selector:
        entity:
          domain: input_number
    min_temperature:
      name: Minimale Temperatur
      selector:
        entity:
          domain: input_number
      default: null
    shelly_phase_1:
      name: Shelly Phase 1
      selector:
        entity:
          domain: switch
    shelly_phase_2:
      name: Shelly Phase 2
      selector:
        entity:
          domain: switch
    shelly_phase_3:
      name: Shelly Phase 3
      selector:
        entity:
          domain: switch
    current_boiler_temperature:
      name: Aktuelle Boilertemperatur
      selector:
        entity:
          domain: sensor
    power_per_stage:
      name: Leistung je Stufe
      selector:
        entity:
          domain: input_number
    min_stage:
      name: Minimale Stufe
      selector:
        entity:
          domain: input_number

trigger:
  # ...existing code...

condition:
  # ...existing code...

action:
  # ...existing code...

mode: single
