blueprint:
  name: Solarüberschussladen des Warmwasserboilers
  description: >
    Steuerung des Warmwasserboilers basierend auf Solarüberschuss und Batterieladezustand.
  domain: automation
  input:
    legionella_temperature:
      name: Legionellen Temperatur
      selector:
        entity:
          domain: input_number
    normal_temperature:
      name: Normale Temperatur
      selector:
        entity:
          domain: input_number
    min_temperature:
      name: Minimale Temperatur
      selector:
        entity:
          domain: input_number
      default: null
    shelly_phase_1:
      name: Shelly Phase 1
      selector:
        entity:
          domain: switch
    shelly_phase_2:
      name: Shelly Phase 2
      selector:
        entity:
          domain: switch
    shelly_phase_3:
      name: Shelly Phase 3
      selector:
        entity:
          domain: switch
    current_boiler_temperature:
      name: Aktuelle Boilertemperatur
      selector:
        entity:
          domain: sensor
    power_per_stage:
      name: Leistung je Stufe
      selector:
        entity:
          domain: input_number
    min_stage:
      name: Minimale Stufe
      selector:
        entity:
          domain: input_number
    last_boiler_charge:
      name: Letzte Boilerladung
      selector:
        entity:
          domain: input_datetime
    min_battery_charge:
      name: Minimaler Batterieladestand
      selector:
        entity:
          domain: input_number
    current_battery_soc:
      name: Aktueller SoC der Batterie
      selector:
        entity:
          domain: sensor
    battery_charge_discharge_power:
      name: Lade-Entladeleistung der Batterie
      selector:
        entity:
          domain: sensor
    grid_feed_in_power:
      name: Netzeinspeisung in W
      selector:
        entity:
          domain: sensor
    boiler_surplus_charging_active:
      name: Boiler Überschussladen aktiv
      selector:
        entity:
          domain: input_boolean
    min_solar_share:
      name: Minimaler Solaranteil in %
      selector:
        entity:
          domain: input_number
    boiler_time_controlled_charging_active:
      name: Boilerladung zeigesteuert aktiv
      selector:
        entity:
          domain: input_boolean
    last_legionella_run:
      name: Letzte Legionellenladung
      selector:
        entity:
          domain: input_datetime
    boiler_surplus_charging_switch:
      name: Boiler Überschussladen
      selector:
        entity:
          domain: switch
    solar_generation:
      name: Solarerzeugung in W
      selector:
        entity:
          domain: sensor

trigger:
  - platform: time_pattern
    seconds: "/30"

condition:
  - condition: state
    entity_id: "{{ input.boiler_surplus_charging_switch }}"
    state: "on"
  - condition: state
    entity_id: "{{ input.boiler_time_controlled_charging_active }}"
    state: "off"
  - condition: state
    entity_id: "{{ input.boiler_surplus_charging_active }}"
    state: "off"

action:
  - service: persistent_notification.create
    data:
      title: "DEBUG: Verfügbare Leistung"
      message: >
        Verfügbare Leistung: {{
          (states('{{ input.solar_generation }}') | float * 
          (states('{{ input.min_solar_share }}') | float / 100)) | round(2)
        }} W

mode: single
