blueprint:
  name: Test Blueprint Fix 3
  description: Testet das Setzen einer Zahl auf eine Input-Number.
  domain: automation
  input:
    test_number:
      name: Testwert
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "A"
          mode: slider
          step: 1
    test_target:
      name: Test-Entität
      selector:
        entity:
          domain: number
          multiple: false

trigger:
  - platform: time_pattern
    seconds: "/10"

variables:
  fixed_value: !input test_number  # Hier speichern wir den Wert als Variable

action:
  - service: number.set_value
    target:
      entity_id: !input test_target
    data:
      value: "{{ fixed_value }}"  # Nutzt die gespeicherte Variable
