blueprint:
  name: Debug Wallbox-Steuerung (Neuer Ansatz)
  description: Test für die Wallbox-Automatisierung mit sicherer Template-Nutzung
  domain: automation
  input:
    invert_net_value:
      name: Vorzeichen umkehren (nur für Einzelwert)
      default: false
      selector:
        boolean:

trigger:
  - platform: homeassistant
    event: start

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_boolean(!input invert_net_value) and !input invert_net_value }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "Wallbox Debug"
              message: "Vorzeichen invertiert: JA"
    default:
      - service: persistent_notification.create
        data:
          title: "Wallbox Debug"
          message: "Vorzeichen invertiert: NEIN"
