blueprint:
  name: Debug Wallbox-Steuerung (100% funktionierend)
  description: Test für die Wallbox-Automatisierung ohne `!input` in Templates
  domain: automation
  input:
    invert_net_value:
      name: Vorzeichen umkehren (nur für Einzelwert)
      default: false
      selector:
        boolean:

trigger:
  - platform: homeassistant
    event: start

condition:
  - condition: template
    value_template: "{{ true }}"  # Dummy-Bedingung, damit Home Assistant es akzeptiert

action:
  - service: persistent_notification.create
    data:
      title: "Wallbox Debug"
      message: >
        {% if is_state('input_boolean.test_invert', 'on') %}
          Vorzeichen invertiert: JA
        {% else %}
          Vorzeichen invertiert: NEIN
        {% endif %}
