blueprint:
  name: Debug Wallbox-Steuerung
  description: Test für die Wallbox-Automatisierung mit Debugging
  domain: automation
  input:
    invert_net_value:
      name: Vorzeichen umkehren (nur für Einzelwert)
      default: false
      selector:
        boolean:

trigger:
  - platform: homeassistant
    event: start

action:
  - service: persistent_notification.create
    data:
      title: "Wallbox Debug"
      message: >
        {% if !input invert_net_value %}
          invert_net_value: false
        {% else %}
          invert_net_value: true
        {% endif %}
