blueprint:
  name: Test Berechnung mit Ladestrom & Min/Max Slider
  description: >
    Wählt sechs Sensoren aus:
    - Multipliziert den ersten Wert mit 1000
    - Zieht den Hausverbrauch & Netzleistung ab
    - Zeigt Batterieentladung, Ladestationsleistung & Ladestrom an
    - Ermöglicht die Eingabe von min/max Ladestrom als Slider
  domain: automation
  homeassistant:
    min_version: "2023.12.0"

  input:
    sensor_1:
      name: Erster Sensor (wird mit 1000 multipliziert)
      selector:
        entity:
          domain: sensor
          device_class: power
    sensor_house_consumption:
      name: Hausverbrauch (W)
      selector:
        entity:
          domain: sensor
          device_class: power
    sensor_2:
      name: Zweiter Sensor (z. B. Netzbezug/-einspeisung, wird abgezogen)
      selector:
        entity:
          domain: sensor
          device_class: power
    sensor_battery:
      name: Batterieentladung (W)
      selector:
        entity:
          domain: sensor
          device_class: power
    sensor_charger:
      name: Ladestationsleistung (W)
      selector:
        entity:
          domain: sensor
          device_class: power
    sensor_charger_current:
      name: Aktueller Ladestrom (A)
      selector:
        entity:
          domain: sensor
          device_class: current

    min_charger_current:
      name: Minimaler Ladestrom (A)
      selector:
        number:
          min: 6
          max: 32
          step: 1
          mode: slider
    max_charger_current:
      name: Maximaler Ladestrom (A)
      selector:
        number:
          min: 6
          max: 32
          step: 1
          mode: slider

variables:
  first_sensor: !input sensor_1
  house_sensor: !input sensor_house_consumption
  second_sensor: !input sensor_2
  battery_sensor: !input sensor_battery
  charger_sensor: !input sensor_charger
  charger_current_sensor: !input sensor_charger_current

  first_value: "{{ states(first_sensor) | float(0) * 1000 }}"
  house_value: "{{ states(house_sensor) | float(0) }}"
  second_value: "{{ states(second_sensor) | float(0) }}"
  battery_value: "{{ states(battery_sensor) | float(0) }}"
  charger_value: "{{ states(charger_sensor) | float(0) }}"
  charger_current_value: "{{ states(charger_current_sensor) | float(0) }}"
  
  min_charger_current_value: !input min_charger_current
  max_charger_current_value: !input max_charger_current

  result: "{{ first_value - second_value - house_value }}"

trigger:
  - platform: time_pattern
    seconds: "/30"

action:
  - service: persistent_notification.create
    data:
      title: "DEBUG: Berechnung mit Ladestrom & Min/Max Slider"
      message: >
        **Erster Sensor:** {{ first_sensor }} → {{ first_value }}  
        **Hausverbrauch:** {{ house_sensor }} → {{ house_value }}  
        **Zweiter Sensor:** {{ second_sensor }} → {{ second_value }}  
        **Batterieentladung:** {{ battery_sensor }} → {{ battery_value }}  
        **Ladestationsleistung:** {{ charger_sensor }} → {{ charger_value }}  
        **Aktueller Ladestrom:** {{ charger_current_sensor }} → {{ charger_current_value }} A  

        **Minimaler Ladestrom (Slider):** {{ min_charger_current_value }} A  
        **Maximaler Ladestrom (Slider):** {{ max_charger_current_value }} A  

        **Berechnung:** ({{ first_value }} - {{ second_value }} - {{ house_value }}) = **{{ result }}**
