blueprint:
  name: Debug Wallbox-Steuerung (FIXED)
  description: Test für die Wallbox-Automatisierung mit funktionierendem Template
  domain: automation
  input:
    invert_net_value:
      name: Vorzeichen umkehren (nur für Einzelwert)
      default: false
      selector:
        boolean:

variables:
  invert_net_value_fixed: !input invert_net_value  # Speichert den Wert zuerst in einer Variablen

trigger:
  - platform: homeassistant
    event: start

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ invert_net_value_fixed }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "Wallbox Debug"
              message: "Vorzeichen invertiert: JA"
    default:
      - service: persistent_notification.create
        data:
          title: "Wallbox Debug"
          message: "Vorzeichen invertiert: NEIN"
