blueprint:
  name: Dynamische Wallbox-Ladesteuerung
  description: > 
    Automatische Anpassung des Ladestroms basierend auf PV-Überschuss, Batteriestatus und Netzbezug. 
    Unterstützt Einzel- oder getrennte Netzeinspeisungswerte.
  domain: automation
  homeassistant:
    min_version: "2023.12.0"
  input:
    min_charge_current:
      name: Minimaler Ladestrom (A)
      description: Der kleinste erlaubte Ladestrom der Wallbox
      default: 6
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "A"
          mode: slider
          step: 1
    max_charge_current:
      name: Maximaler Ladestrom (A)
      description: Der höchste erlaubte Ladestrom der Wallbox
      default: 16
      selector:
        number:
          min: 6
          max: 32
          unit_of_measurement: "A"
          mode: slider
          step: 1
    min_battery_soc:
      name: Minimaler Batterieladestand (%)
      description: Mindestwert, bevor das Laden beginnt.
      default: 20
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1
    net_power:
      name: Netzeinspeisung/-bezug (W) [Einzelwert]
      description: Eine einzelne Entität, die positiv oder negativ sein kann.
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    invert_net_value:
      name: Vorzeichen umkehren (nur für Einzelwert)
      description: Falls die Netzeinspeisung als positiver Wert dargestellt wird, aktiviere diese Option.
      default: false
      selector:
        boolean:
    net_export:
      name: Netzeinspeisung (W) [Getrennte Werte]
      description: Falls die Netzeinspeisung separat gemessen wird.
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    net_import:
      name: Netzbezug (W) [Getrennte Werte]
      description: Falls der Netzbezug separat gemessen wird.
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    charger_power:
      name: Aktuelle Ladeleistung (W)
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    charger_current:
      name: Aktueller Ladestrom (A)
      selector:
        entity:
          domain: number
          multiple: false
    automation_switch:
      name: Automatisierungsschalter
      selector:
        entity:
          domain: input_boolean
    house_consumption:
      name: Hausverbrauch (W)
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    pv_power:
      name: PV-Leistung (W)
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    charger_status:
      name: Wallbox Status / Mode
      selector:
        entity:
          domain: sensor
          multiple: false

trigger:
  - platform: state
    entity_id: !input charger_status
    to: "Waiting"
  - platform: state
    entity_id: !input pv_power
  - platform: state
    entity_id: !input house_consumption
  - platform: state
    entity_id: !input net_power
  - platform: state
    entity_id: !input net_export
  - platform: state
    entity_id: !input net_import
  - platform: time_pattern
    seconds: "/30"

condition:
  - condition: state
    entity_id: !input automation_switch
    state: "on"
  - condition: numeric_state
    entity_id: !input min_battery_soc
    above: !input min_battery_soc
  - condition: state
    entity_id: !input charger_status
    state: "Waiting"

action:
  - service: number.set_value
    target:
      entity_id: !input charger_current
    data:
      value: >
        {% set net_power = states(!input net_power) | float(none) %}
        {% set net_export = states(!input net_export) | float(none) %}
        {% set net_import = states(!input net_import) | float(none) %}
        {% set house_consumption = states(!input house_consumption) | float(0) %}
        {% set pv_power = states(!input pv_power) | float(0) %}
        {% set min_current = !input min_charge_current | int %}
        {% set max_current = !input max_charge_current | int %}
        {% set conversion_factor = 219 %}  # Umrechnungsfaktor W -> A für dreiphasige Ladung

        {# Falls eine einzelne Netzeinspeisung vorhanden ist, wird sie genutzt #}
        {% if net_power != none %}
          {% if is_state(!input invert_net_value, "true") %}
            {% set net_power = net_power * -1 %}
          {% endif %}
          {% set available_power = net_power %}
        {# Falls getrennte Werte für Einspeisung & Bezug genutzt werden #}
        {% elif net_export != none and net_import != none %}
          {% set available_power = net_export - net_import %}
        {# Falls keine Netzwerte vorhanden sind, wird der PV-Überschuss berechnet #}
        {% else %}
          {% set available_power = pv_power - house_consumption %}
        {% endif %}

        {% set new_current = (available_power / conversion_factor) | round(0) %}

        {% if new_current > max_current %}
          {{ max_current }}
        {% elif new_current < min_current %}
          {{ min_current }}
        {% else %}
          {{ new_current }}
        {% endif %}
