blueprint:
  name: Dynamische Wallbox-Ladesteuerung
  description: > 
    Automatische Anpassung des Ladestroms basierend auf PV-Überschuss, Batteriestatus und Netzbezug.
    Du kannst entweder eine einzelne Netzeinspeisungs-Entität oder getrennte Werte für Bezug & Einspeisung eingeben.
  domain: automation
  homeassistant:
    min_version: "2023.12.0"
  input:
    min_charge_current:
      name: Minimaler Ladestrom (A)
      default: 6
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "A"
          mode: slider
          step: 1
    max_charge_current:
      name: Maximaler Ladestrom (A)
      default: 16
      selector:
        number:
          min: 6
          max: 32
          unit_of_measurement: "A"
          mode: slider
          step: 1
    charger_current:
      name: Aktueller Ladestrom (A)
      selector:
        entity:
          domain: number
          multiple: false

action:
  - service: number.set_value
    target:
      entity_id: !input charger_current
    data:
      value: >
        {% set min_current = (!input min_charge_current) | int %}
        {% set max_current = (!input max_charge_current) | int %}
        
        {% if min_current > max_current %}
          {{ max_current }}
        {% else %}
          {{ min_current }}
        {% endif %}
