blueprint:
  name: Test Entitätswert
  description: >
    Wählt eine beliebige Entität aus und gibt deren aktuellen Wert aus.
  domain: automation
  homeassistant:
    min_version: "2023.12.0"

  input:
    any_sensor:
      name: Beliebiger Sensor
      selector:
        entity:
          domain: sensor

variables:
  selected_sensor: !input any_sensor

trigger:
  - platform: time_pattern
    seconds: "/30"

action:
  - service: persistent_notification.create
    data:
      title: "DEBUG: Sensorwert"
      message: >
        **Gewählte Entität:** {{ selected_sensor }}  
        **Aktueller Wert:** {{ states(selected_sensor) }}
