blueprint:
  name: Dynamische Wallbox-Ladesteuerung
  description: > 
    Automatische Anpassung des Ladestroms basierend auf PV-Überschuss, Batteriestatus und Netzbezug.
    Du kannst entweder eine einzelne Netzeinspeisungs-Entität oder getrennte Werte für Bezug & Einspeisung eingeben.
  domain: automation
  homeassistant:
    min_version: "2023.12.0"
  input:
    min_charge_current:
      name: Minimaler Ladestrom (A)
      default: 6
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "A"
          mode: slider
          step: 1
    max_charge_current:
      name: Maximaler Ladestrom (A)
      default: 16
      selector:
        number:
          min: 6
          max: 32
          unit_of_measurement: "A"
          mode: slider
          step: 1
    min_battery_soc:
      name: Minimaler Batterieladestand (%)
      default: 20
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
          step: 1
    net_power:
      name: Netzeinspeisung/-bezug (W) [Einzelwert]
      description: Falls nicht genutzt, lasse dieses Feld leer.
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    invert_net_value:
      name: Vorzeichen umkehren (nur für Einzelwert)
      default: false
      selector:
        boolean:
    net_export:
      name: Netzeinspeisung (W) [Getrennte Werte]
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    net_import:
      name: Netzbezug (W) [Getrennte Werte]
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    charger_power:
      name: Aktuelle Ladeleistung (W)
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    charger_current:
      name: Aktueller Ladestrom (A)
      selector:
        entity:
          domain: number
          multiple: false
    automation_switch:
      name: Automatisierungsschalter
      selector:
        entity:
          domain: input_boolean
    house_consumption:
      name: Hausverbrauch (W)
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    pv_power:
      name: PV-Leistung (W)
      selector:
        entity:
          domain: sensor
          device_class: power
          multiple: false
    charger_status:
      name: Wallbox Status / Mode
      selector:
        entity:
          domain: sensor
          multiple: false

trigger:
  - platform: state
    entity_id: !input charger_status
    to: "Waiting"
  - platform: time_pattern
    seconds: "/30"

condition:
  - condition: state
    entity_id: !input automation_switch
    state: "on"
  - condition: numeric_state
    entity_id: !input min_battery_soc
    above: !input min_battery_soc
  - condition: state
    entity_id: !input charger_status
    state: "Waiting"

action:
  - service: number.set_value
    target:
      entity_id: !input charger_current
    data:
      value: >
        {% set net_power = states(entity_id=(!input net_power|string)) | float(0) %}
        {% set net_export = states(entity_id=(!input net_export|string)) | float(0) %}
        {% set net_import = states(entity_id=(!input net_import|string)) | float(0) %}
        {% set house_consumption = states(entity_id=(!input house_consumption|string)) | float(0) %}
        {% set pv_power = states(entity_id=(!input pv_power|string)) | float(0) %}
        {% set min_current = (!input min_charge_current|string) | int %}
        {% set max_current = (!input max_charge_current|string) | int %}
        {% set conversion_factor = 219 %}

        {# Falls eine einzelne Netzeinspeisung vorhanden ist, wird sie genutzt #}
        {% if net_power != 0 %}
          {% if is_state(entity_id=(!input invert_net_value|string), state="true") %}
            {% set net_power = net_power * -1 %}
          {% endif %}
          {% set available_power = net_power %}
        {# Falls getrennte Werte für Einspeisung & Bezug genutzt werden #}
        {% elif net_export != 0 or net_import != 0 %}
          {% set available_power = net_export - net_import %}
        {# Falls keine Netzwerte vorhanden sind, wird der PV-Überschuss berechnet #}
        {% else %}
          {% set available_power = pv_power - house_consumption %}
        {% endif %}

        {% set new_current = (available_power / conversion_factor) | round(0) %}

        {% if new_current > max_current %}
          {{ max_current }}
        {% elif new_current < min_current %}
          {{ min_current }}
        {% else %}
          {{ new_current }}
        {% endif %}
