blueprint:
  name: Test PV-Leistung
  description: >
    Gibt die aktuelle PV-Leistung aus.
  domain: automation
  homeassistant:
    min_version: "2023.12.0"

  input:
    pv_power:
      name: PV-Leistung (W)
      selector:
        entity:
          domain: sensor
          device_class: power

trigger:
  - platform: time_pattern
    seconds: "/30"

action:
  - service: persistent_notification.create
    data:
      title: "DEBUG: PV-Leistung"
      message: >
        **PV-Leistung (raw ID):** !input pv_power  
        **PV-Leistung (Wert):** {{ states('!input pv_power') }}
