blueprint:
  name: Test Berechnung mit zwei Sensoren
  description: >
    Wählt zwei beliebige Sensoren aus, multipliziert den ersten mit 1000 und zieht den zweiten davon ab.
  domain: automation
  homeassistant:
    min_version: "2023.12.0"

  input:
    sensor_1:
      name: Solarerzeugung in KW
      selector:
        entity:
          domain: sensor
    sensor_2:
      name: Netzbezug in W
      selector:
        entity:
          domain: sensor

variables:
  var_solar_power: !input solar_power 
  var_grid_power: !input grid_power
  var_solar_power: "{{ states(var_solar_power) | float(0) * 1000 }}"
  var_grid_power: "{{ states(var_grid_power) | float(0) * 1000 }}"
  result: "{{ var_solar_power - var_grid_power }}"

trigger:
  - platform: time_pattern
    seconds: "/30"

action:
  - service: persistent_notification.create
    data:
      title: "DEBUG: Berechnung"
      message: >
        **Erster Sensor:** {{ var_solar_power }} → {{ first_value }}  
        **Zweiter Sensor:** {{ var_grid_power }} → {{ var_grid_power }}  
        **Berechnung:** ({{ var_solar_power }} - {{ var_grid_power }}) = **{{ result }}**
