blueprint:
  name: Test Berechnung mit zwei Sensoren
  description: >
    Wählt zwei beliebige Sensoren aus, multipliziert den ersten mit 1000 und zieht den zweiten davon ab.
  domain: automation
  homeassistant:
    min_version: "2023.12.0"

  input:
    sensor_1:
      name: Erster Sensor (wird mit 1000 multipliziert)
      selector:
        entity:
          domain: sensor
    sensor_2:
      name: Zweiter Sensor (wird abgezogen)
      selector:
        entity:
          domain: sensor

variables:
  first_sensor: !input sensor_1
  second_sensor: !input sensor_2
  first_value: "{{ states(first_sensor) | float(0) * 1000 }}"
  second_value: "{{ states(second_sensor) | float(0) * 1000 }}"
  result: "{{ first_value - second_value }}"

trigger:
  - platform: time_pattern
    seconds: "/30"

action:
  - service: persistent_notification.create
    data:
      title: "DEBUG: Berechnung"
      message: >
        **Erster Sensor:** {{ first_sensor }} → {{ first_value }}  
        **Zweiter Sensor:** {{ second_sensor }} → {{ second_value }}  
        **Berechnung:** ({{ first_value }} - {{ second_value }}) = **{{ result }}**
