blueprint:
  name: Test Wallbox Steuerung (Minimal)
  description: >
    Einfache Steuerung des Ladestroms – Testversion ohne Berechnungen.
  domain: automation
  homeassistant:
    min_version: "2023.12.0"

  input:
    charger_current:
      name: Aktueller Ladestrom (A)
      selector:
        entity:
          domain: number

trigger:
  - platform: time_pattern
    seconds: "/30"

action:
  - service: number.set_value
    target:
      entity_id: !input charger_current
    data:
      value: "10"
