blueprint:
  name: Test Wallbox Steuerung (Verfügbare Leistung)
  description: >
    Berechnet die verfügbare Ladeleistung basierend auf PV-Erzeugung, Batterieladung und Netzeinspeisung.
  domain: automation
  homeassistant:
    min_version: "2023.12.0"

  input:
    charger_current:
      name: Aktueller Ladestrom (A)
      selector:
        entity:
          domain: number
    house_consumption:
      name: Hausverbrauch (W)
      selector:
        entity:
          domain: sensor
          device_class: power
    pv_power:
      name: PV-Leistung (W)
      selector:
        entity:
          domain: sensor
          device_class: power
    battery_power:
      name: Batterie Lade-/Entladeleistung (W)
      selector:
        entity:
          domain: sensor
          device_class: power
    battery_soc:
      name: Batteriestand (SoC %)
      selector:
        entity:
          domain: sensor
          device_class: battery
    net_power:
      name: Netzeinspeisung/-bezug (W)
      selector:
        entity:
          domain: sensor
          device_class: power

trigger:
  - platform: time_pattern
    seconds: "/30"

action:
  - service: persistent_notification.create
    data:
      title: "DEBUG: Sensorwerte"
      message: >
        **Überprüfe, ob alle Entitäts-IDs korrekt übergeben wurden:**
        
        - `pv_power`: {{ this.pv_power }}
        - `house_consumption`: {{ this.house_consumption }}
        - `battery_power`: {{ this.battery_power }}
        - `net_power`: {{ this.net_power }}
        - `battery_soc`: {{ this.battery_soc }}

        **Werte aus states():**
        
        - `pv_power`: {{ states(this.pv_power) }}
        - `house_consumption`: {{ states(this.house_consumption) }}
        - `battery_power`: {{ states(this.battery_power) }}
        - `net_power`: {{ states(this.net_power) }}
        - `battery_soc`: {{ states(this.battery_soc) }}

        Falls hier "unknown" oder "none" steht, prüfe, ob die Sensoren in den Blueprint-Inputs richtig ausgewählt wurden!
