blueprint:
  name: Test Wallbox Steuerung (Verf端gbare Leistung)
  description: >
    Berechnet die verf端gbare Ladeleistung basierend auf PV-Erzeugung, Batterieladung und Netzeinspeisung.
  domain: automation
  homeassistant:
    min_version: "2023.12.0"

  input:
    charger_current:
      name: Aktueller Ladestrom (A)
      selector:
        entity:
          domain: number
    house_consumption:
      name: Hausverbrauch (W)
      selector:
        entity:
          domain: sensor
          device_class: power
    pv_power:
      name: PV-Leistung (W)
      selector:
        entity:
          domain: sensor
          device_class: power
    battery_power:
      name: Batterie Lade-/Entladeleistung (W)
      selector:
        entity:
          domain: sensor
          device_class: power
    battery_soc:
      name: Batteriestand (SoC %)
      selector:
        entity:
          domain: sensor
          device_class: battery
    net_power:
      name: Netzeinspeisung/-bezug (W)
      selector:
        entity:
          domain: sensor
          device_class: power

trigger:
  - platform: time_pattern
    seconds: "/30"

action:
  - service: persistent_notification.create
    data:
      title: "Ladezustand & Verf端gbare Leistung"
      message: >
        {% set pv_power = states[input.pv_power] | float(0) %}
        {% set house_consumption = states[input.house_consumption] | float(0) %}
        {% set battery_power = states[input.battery_power] | float(0) %}
        {% set net_power = states[input.net_power] | float(0) %}
        {% set battery_soc = states[input.battery_soc] | float(0) %}

        {% set available_power = pv_power + battery_power + net_power - house_consumption %}

        Batteriestand: {{ battery_soc }}%  
        Verf端gbare Ladeleistung: {{ available_power }} W
